---
default_stages: [commit]
default_language_version:
    python: python3
repos:
  # Python
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        language: python
        additional_dependencies:
          - flake8-blind-except
          - flake8-builtins
          - flake8-tidy-imports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
        language: python

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    - id: docformatter
      args:
        - --in-place
        - --pre-summary-newline
        - --wrap-summaries=0
