# Generated by Django 4.1b1 on 2022-07-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The plain-language identifier of the Category",
                        max_length=200,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Text to use for the role signup message explaining the purpose of the Category",
                    ),
                ),
                (
                    "self_assignable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the bot should allow self-assignment of roles in this Category",
                    ),
                ),
                (
                    "unique",
                    models.BooleanField(
                        default=False,
                        help_text="Set to TRUE if only one role in this category may be active at a time",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "role categories",
            },
        ),
        migrations.CreateModel(
            name="DiscordRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_role_id",
                    models.CharField(
                        help_text="The unique Discord object ID for the Role",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name assigned to the Role in Discord",
                        max_length=200,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Emoji (unicode or discord emoji <name:id> tag) to associate with the Role; appears on signup buttons",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="roles.rolecategory",
                    ),
                ),
            ],
        ),
    ]
